#!/bin/bash

RUBY_VERSION=$1
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
gem install bundler
rbenv rehash
echo "export GEM_HOME=/app/.data/gems" >> ~/.bashrc
echo "export GEM_PATH=/app/.data/gems" >> ~/.bashrc
echo "export PATH=/app/.data/gems/bin:\$PATH" >> ~/.bashrc
source ~/.bashrc
