#!/bin/bash

RUBY_VERSION=$1
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
gem install --install-dir $GLOBAL_GEMS_PATH bundler

if [ ${@:2} ]; then
  gem install --install-dir $GLOBAL_GEMS_PATH "${@:2}"
fi

rbenv rehash
