#!/bin/bash

RUBY_VERSION=$1
GLOBAL_GEMS_PATH=/root/gems
LOCAL_GEMS_PATH=/app/.data/gems

GEM_HOME=$GLOBAL_GEMS_PATH
GEM_PATH=$GLOBAL_GEMS_PATH

rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
gem install bundler
rbenv rehash

echo "export GEM_HOME=$LOCAL_GEMS_PATH" >> ~/.bashrc
echo "export GEM_PATH=$LOCAL_GEMS_PATH:$GLOBAL_GEMS_PATH" >> ~/.bashrc
echo "export PATH=/app/.data/gems/bin:\$PATH" >> ~/.bashrc
source ~/.bashrc
