#!/bin/bash

NODE_VERSION=$1
source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION
echo "export PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:\$PATH" >> ~/.bashrc

if [ ${@:2} ]; then
  npm install -g "${@:2}"
fi
